wandb_version: 1

model_name:
  desc: null
  value: llama-3/transformers/8b-hf/1
max_length:
  desc: null
  value: 1284
batch_size:
  desc: null
  value: 8
r:
  desc: null
  value: 16
lora_alpha:
  desc: null
  value: 32
lora_dropout:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 2.0e-05
num_epochs:
  desc: null
  value: 1
num_warmup_steps:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.42.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1720334722
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.10
      5: 0.17.4
      6: 4.42.3
      8:
      - 2
      - 5
      - 13
      13: linux-x86_64
